In [35]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 
import seaborn as sns 
import sklearn 


In [36]:
import pandas as pd

df = pd.read_csv("evaluation.csv",delimiter=';',nrows=1000)

df.head()

Unnamed: 0                                              title  \
0           0  Sanders back in U.S. Senate, blasts 'coloniali...   
1           1  Kremlin: Syria peoples' congress being 'active...   
2           2   Oregon Cop Convicted Of Shattering Biker’s Co...   
3           3   Twitter Erupts With Glee Over #CruzSexScandal...   
4           4  MUST WATCH VIDEO: Obama Tries To Trash Trump B...   

                                                text  label  
0  WASHINGTON (Reuters) - Democratic U.S. preside...      1  
1  MOSCOW (Reuters) - A proposal to convene a con...      1  
2  In a baffling fit of rage, an Oregon State Pol...      0  
3  The last thing any politician running for the ...      0  
4  This is too good to miss! Mr. Teleprompter did...      0

In [37]:
df1.columns

Index([';title;text;label'], dtype='object')

In [38]:
for i in range(len(df)):
    print(df.iloc[i])


Unnamed: 0                                                    0
title         Sanders back in U.S. Senate, blasts 'coloniali...
text          WASHINGTON (Reuters) - Democratic U.S. preside...
label                                                         1
Name: 0, dtype: object
Unnamed: 0                                                    1
title         Kremlin: Syria peoples' congress being 'active...
text          MOSCOW (Reuters) - A proposal to convene a con...
label                                                         1
Name: 1, dtype: object
Unnamed: 0                                                    2
title          Oregon Cop Convicted Of Shattering Biker’s Co...
text          In a baffling fit of rage, an Oregon State Pol...
label                                                         0
Name: 2, dtype: object
Unnamed: 0                                                    3
title          Twitter Erupts With Glee Over #CruzSexScandal...
text          The last thing any po

In [39]:
df.isna().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  1000 non-null   int64 
 1   title       1000 non-null   object
 2   text        1000 non-null   object
 3   label       1000 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 31.4+ KB


In [41]:
import re
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [42]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

In [43]:
def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = ' '.join([stemmer.stem(word) for word in text.split() if word not in stop_words])
    return text
df['cleaned_text'] = df['text'].apply(clean_text)

In [44]:
df.head()

Unnamed: 0                                              title  \
0           0  Sanders back in U.S. Senate, blasts 'coloniali...   
1           1  Kremlin: Syria peoples' congress being 'active...   
2           2   Oregon Cop Convicted Of Shattering Biker’s Co...   
3           3   Twitter Erupts With Glee Over #CruzSexScandal...   
4           4  MUST WATCH VIDEO: Obama Tries To Trash Trump B...   

                                                text  label  \
0  WASHINGTON (Reuters) - Democratic U.S. preside...      1   
1  MOSCOW (Reuters) - A proposal to convene a con...      1   
2  In a baffling fit of rage, an Oregon State Pol...      0   
3  The last thing any politician running for the ...      0   
4  This is too good to miss! Mr. Teleprompter did...      0   

                                        cleaned_text  
0  washington reuter democrat us presidenti hope ...  
1  moscow reuter propos conven congress syria eth...  
2  baffl fit rage oregon state polic offic convic...  
3  last thing politician run presid need neg scan...  
4  good miss mr teleprompt well went script appea...

In [45]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['cleaned_text'])
y = df['label']
y

0      1
1      1
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: label, Length: 1000, dtype: int64

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0], dtype=int64)

In [58]:
con=confusion_matrix(y_test,y_pred)
print(con)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[ 89   2]
 [  7 102]]
0.955


In [66]:
# knn
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
y_knn_pred=knn.predict(X_test)


In [67]:
con=confusion_matrix(y_test,y_knn_pred)
print(con)
acc=accuracy_score(y_test,y_knn_pred)
print(acc)

[[ 68  23]
 [  9 100]]
0.84


In [69]:
  # decision tree 
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_dt_pred=dt.predict(X_test)

In [70]:
con=confusion_matrix(y_test,y_dt_pred)
print(con)
acc=accuracy_score(y_test,y_dt_pred)
print(acc)


[[ 89   2]
 [  4 105]]
0.97


In [71]:
# random forest 
from sklearn.ensemble import RandomForestClassifier
rr=RandomForestClassifier()


In [73]:
rr.fit(X_train,y_train)
y_rr_pred=rr.predict(X_test)

In [74]:
con=confusion_matrix(y_test,y_rr_pred)
print(con)
acc=accuracy_score(y_test,y_rr_pred
                   )
print(acc)


[[ 90   1]
 [  6 103]]
0.965


In [85]:
# ada boost 
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier()
ada.fit(X_train,y_train)
y_ada_pred=ada.predict(X_test)

C:\Users\rajas\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [86]:
con=confusion_matrix(y_test,y_ada_pred)
print(con)
acc=accuracy_score(y_test,y_ada_pred
                   )
print(acc)


[[ 89   2]
 [  4 105]]
0.97
